### ISSUE TITLE
Command-line argument --threads should be --workers

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-cpp#12]
To match the naming convention in target parameters, the command-line option for Cpp generated programs should be changed from `-t` and `--threads` to `-w` and `--workers`.

**Comment by cmnrd** [comment]
I am closing this because this already implemented. With a more or less recent lfc, `--help` on the resulting binary prints the following:
```
  -w, --workers 'unsigned'    the number of worker threads used by the scheduler (default: 4)
  -o, --timeout 'FLOAT UNIT'  Time after which the execution is aborted. (default: 0 nsecs)
  -k, --keepalive             Continue execution even when there are no events to process.
  -f, --fast                  Allow logical time to run faster than physical time.
      --help                  Print help
```

Also note that the CLI parsing is code generated by the LF compiler and not part of reactor-cpp.

**Comment by edwardalee** [comment]
A great, I've updated the website docs.
