### ISSUE TITLE
Prevent user code from modifying multiport contents

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/reactor-cpp#30]
So far, multiports were implemented as plain vectors of ports. https://github.com/lf-lang/reactor-cpp/pull/24 introduces a new MultiPort class to organize ports in a smarter way. This is mostly motivated by an optimazation for sparse communication. In the discussion of https://github.com/lf-lang/reactor-cpp/pull/24 it became clear that both the old and the new solution allow user code to modify the multiport. For instance users could add or remove ports. Ideally we can use the new dedicated Multiport class to restrict user access and allow only safe operations.

**Comment by revol-xut** [comment]
Working on it

**Comment by revol-xut** [comment]
pull request are open #33
